### ISSUE TITLE
Getting constant forecasts from ForecastPFN

### ISSUE THREAD

**Issue by abdulfatir** [abacusai/ForecastPFN#2]
Hi!

Thanks for releasing the code and the model. I tried running the evaluation on the illness dataset as described in the README. I am able to reproduce the MSE value reported in the paper; however, the actual forecast is constant. Please see the figure below.

![image](https://github.com/abacusai/ForecastPFN/assets/4028948/7d848f5e-4c83-4962-b3ed-46d11a58ad39)

After running the evaluation, I used the following code for plotting. 

```py
import numpy as np
import matplotlib.pyplot as plt

preds = np.load(
    "results/ForecastPFN_ili_sl36_ll18_pl14_timebudget_None_trainbudget_50_model-path_ForecastPFN_itr_0/pred.npy"
)
true = np.load(
    "results/ForecastPFN_ili_sl36_ll18_pl14_timebudget_None_trainbudget_50_model-path_ForecastPFN_itr_0/true.npy"
)

ax = plt.gca()
for j in range(5):
    color = next(ax._get_lines.prop_cycler)["color"]
    ax.plot(preds[j].squeeze(), color=color, label="True")
    ax.plot(true[j].squeeze(), color=color, linestyle="--", label="Predicted")

ax.legend()
plt.show()
```

The model also seems to give constant forecasts on other datasets (although I did not test that rigorously). Can you explain what could be going on here?

**Comment by abdulfatir** [comment]
Here's the plot for ETTh1:

![image](https://github.com/abacusai/ForecastPFN/assets/4028948/9402d948-d661-4ced-9124-e70516c6742c)

**Comment by dooleys** [comment]
After taking a look, it seems to be an artifact of the scaling procedure after the StandardScaler and our robust scaler.
https://github.com/abacusai/ForecastPFN/blob/fe7a99692b8a7ca12831cc45b81f5abe89d7d943/benchmark/exp/exp_ForecastPFN.py#L80
On illness dataset, it appears that the clipping makes the `history` (near) constant 0 or 1s and then this results in the constant output.

I've looked into other scaling or clipping techniques and what is here still yields better performance across the datasets and configurations.
